spring:
  datasource:
#    ========数据源基本配置========
    username: root
    password: hjb3344521
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/monster?characterEncoding=UTF-8&&serverTimezone=GMT
    type: com.alibaba.druid.pool.DruidDataSource
#    ========下面为druid连接池的补充设置，应用到上面所有数据源中========
#    初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
#    配置获取连接等待超时的时间
    maxWait: 60000
#    配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
#    配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
#    打开PSCache，并且指定每个连接上PSCache的大小
    poolPrepareStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
#    配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
#    合并多个DruidDataSource的监控数据
    useBlobalDataSourceStat: true
#    通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml